version: '3.8'
services:
  backend:
    build:
      context: ../../Go/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge