services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
