###

GET http://localhost:8080/products

###

GET http://localhost:8080/products/1

###

POST http://localhost:8080/products
Content-Type: application/json

{
  "Name": "Nowy Produkt1",
  "Description": "Opis1...",
  "Price": 99.991
}

###

PUT http://localhost:8080/products/1
Content-Type: application/json

{
  "Name": "Zaktualizowany Produkt",
  "Description": "Zaktualizowany opis...",
  "Price": 109.99
}

###

DELETE http://localhost:8080/products/1

###

POST http://localhost:8080/carts
Content-Type: application/json

{}

###

GET http://localhost:8080/carts/1

###

POST http://localhost:8080/carts/1/items
Content-Type: application/json

{
  "ProductID": 2,
  "Quantity": 3
}

###

DELETE http://localhost:8080/carts/1/items/1

###