###

GET http://localhost:8080/products

###

GET http://localhost:8080/products/1

###

POST http://localhost:8080/products
Content-Type: application/json

{
  "Name": "Nowy Produkt",
  "Description": "Opis produktu",
  "Price": 99.99,
  "CategoryID": 1
}

###

PUT http://localhost:8080/products/1
Content-Type: application/json

{
  "Name": "Zaktualizowany Produkt",
  "Description": "Zaktualizowany opis...",
  "Price": 109.99,
  "CategoryID": 1
}

###

DELETE http://localhost:8080/products/1

###

POST http://localhost:8080/carts
Content-Type: application/json

{}

###

GET http://localhost:8080/carts/1

###

POST http://localhost:8080/carts/1/items
Content-Type: application/json

{
  "ProductID": 2,
  "Quantity": 3
}

###

DELETE http://localhost:8080/carts/1/items/1

###

POST http://localhost:8080/categories
Content-Type: application/json

{
  "Name": "Elektronika",
  "Description": "Wszystko co związane z elektroniką"
}

###

GET http://localhost:8080/categories

###

GET http://localhost:8080/categories/1

###

PUT http://localhost:8080/categories/1
Content-Type: application/json

{
  "Name": "Nowa Elektronika",
  "Description": "Zaktualizowany opis dla kategorii"
}

###

DELETE http://localhost:8080/categories/1

###

