name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.15.0'

      - name: Build backend
        run: |
          cd Oauth2/oauth2-server
          npm install

      - name: Build frontend
        run: |
          cd Oauth2/oauth2-client
          npm install
          npm run build

      - name: Build Docker images
        run: |
          docker build -t yehorsavchenko/my-backend-image:latest ./Oauth2/oauth2-server
          docker build -t yehorsavchenko/my-frontend-image:latest ./Oauth2/oauth2-client

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images
        run: |
          docker push yehorsavchenko/my-backend-image:latest
          docker push yehorsavchenko/my-frontend-image:latest

  notify:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.office365.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Build Notification
          body: The application has been successfully built and Docker images have been pushed.
          to: recipient@example.com
          from: ${{ secrets.EMAIL_USERNAME }}
          secure: true