name: SonarCloud Analysis

on:
  push:
    branches:
      - master

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd Go
          go get -t -v ./...
          cd ../React/my-react-app
          npm install
          npm run build

      - name: Run tests and generate coverage
        run: |
          cd Go
          go test -coverprofile=coverage.out ./...
          cd ../React/my-react-app
          npm test -- --coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=your_project_key
            -Dsonar.organization=your_organization
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}